version: '3.8'

services:
  web:
    restart: always
    image: tools_app_web_backend:latest
    tty: true
    build: .
    # запуск чего-то кроме рансервер
    command: sh -c "poetry run python manage.py migrate && 
                    poetry run python manage.py runserver 0.0.0.0:8000"
    container_name: tools_app_django
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
volumes:
  db:
